### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by lukemcar** [garettB/shopify-flask-example#2]
This code only allows for one user and you have to uninstall and reinstall the app in shopify if you restart your service. The code is so badly organized that I can't unravel this mess. I appreciate your effort for trying to give an example but its so poorly written that it's more of a rabbits whole in alice and wonderland then a guide.

**Comment by garettB** [comment]
Hi,

My apologies my free work was not up to your standards. If you feel that strongly, perhaps providing constructive criticism or submitting a PR would be a better approach?

This was never meant to be a fully functional sample, it is a starting point. I mentioned that it will need additional supports to continue to work.

Please try to be a nicer person.

**Comment by Malthehave** [comment]
I think this code is absolutely fine! It sure did provide me with a much better understanding of the architecture behind a shopify app
